# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'MarketCap' do
  pod 'VPSocketIO', '~> 1.0.5' 
  # Pods for MarketCap
end

  target 'MarketCapTests' do
    inherit! :search_paths
    # Pods for testing
  end
